identifier: l2wagai34bd7b155
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /home/aslan/Documents/my-blog
distFolder: dist/my-blog
outDir: /home/aslan/Documents/my-blog/dist/static
handle404: ''
allowErrorCollect: false
